backend:
  name: github
  repo: ari-motors-team/elektrotransporter-vergleich
  branch: dev
  # auth_type: pkce
  # app_id: aac348df96d3bb0a9253a7124cbe6af595c462fcfcdc36a09b0d0616c81eebe0

media_folder: public/images
public_folder: /images
local_backend: true

i18n:
  structure: multiple_folders
  locales: [en, de]
  default_locale: en

collections:
  - label: "Pages"
    name: "pages"
    identifier_field: path
    folder: "content/pages"
    create: true
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Path", name: "path", widget: "string", i18n: duplicate }
      - label: "Description"
        name: "description"
        widget: "text"
        i18n: true
      - { label: Image, name: src, widget: image, i18n: duplicate }
      - label: "Content"
        name: "content"
        widget: "list"
        summary: "{{fields.name}}"
        i18n: true
        required: false
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Markdown", name: "markdown", widget: "markdown" }

  - label: "Blog"
    name: "blog"
    folder: "content/posts"
    create: true
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Slug", name: "slug", widget: "string", i18n: duplicate }
      - label: "Published at"
        name: "publishedAt"
        widget: "date"
        default: ""
        format: "MM/DD/YYYY"
        i18n: true
      - label: "Description"
        name: "description"
        widget: "text"
        i18n: true
      - { label: Image, name: src, widget: image, i18n: duplicate }
      - { label: "Preview", name: "preview", widget: "text", i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
      # cars wheelbase, typeClass,category, availability, fields are missing 
  - label: "Vehicles"
    name: "vehicles"
    folder: "content/vehicles"
    create: true
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }

      - { label: "Price", name: "price", widget: "number", i18n: duplicate }
      # - label: "Published at"
      #   name: "publishedAt"
      #   widget: "date"
      #   default: ""
      #   format: "MM/DD/YYYY"
      #   i18n: true
      - label: "Description"
        name: "description"
        widget: "markdown"
        i18n: true
      - { label: Image, name: src, widget: image, i18n: duplicate }
      - { label: "Preview", name: "preview", widget: "text", i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
      - label: "Loadingweight"
        name: "loadingWeight"
        widget: "object"
        summary: "{{fields.key}}: {{fields.value}}"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Value", name: "value", widget: "number" }
          - { label: "baseUnit", name: "baseUnit", widget: "string" }
      - label: "maxSpeed"
        name: "maxSpeed"
        widget: "object"
        summary: "{{fields.key}}: {{fields.value}}"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Value", name: "value", widget: "number" }
          - { label: "baseUnit", name: "baseUnit", widget: "string" }
      - label: "Range-230V"
        name: "Range230V"
        widget: "object"
        summary: "{{fields.key}}: {{fields.value}}"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Value", name: "value", widget: "number" }
          - { label: "baseUnit", name: "baseUnit", widget: "string" }
      - label: "Range-Lithium"
        name: "RangeLithium"
        widget: "object"
        summary: "{{fields.key}}: {{fields.value}}"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Value", name: "value", widget: "number" }
          - { label: "baseUnit", name: "baseUnit", widget: "string" }
      - label: "chargingTime-230V"
        name: "chargingTime230V"
        widget: "object"
        summary: "{{fields.key}}: {{fields.value}}"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Value", name: "value", widget: "number" }
          - { label: "baseUnit", name: "baseUnit", widget: "string" }
      - label: "chargingTime-Lithium"
        name: "chargingTimeLithium"
        widget: "object"
        summary: "{{fields.key}}: {{fields.value}}"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Value", name: "value", widget: "number" }
          - { label: "baseUnit", name: "baseUnit", widget: "string" }
      - label: "chargingTime-Fast"
        name: "chargingTimeFast"
        widget: "object"
        summary: "{{fields.key}}: {{fields.value}}"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Value", name: "value", widget: "number" }
          - { label: "baseUnit", name: "baseUnit", widget: "string" }
      - label: "battery-Capacity"
        name: "batteryCapacity"
        widget: "object"
        summary: "{{fields.key}}: {{fields.value}}"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Value", name: "value", widget: "number" }
          - { label: "baseUnit", name: "baseUnit", widget: "string" }
      - label: "Seats"
        name: "seats"
        widget: "object"
        summary: "{{fields.key}}: {{fields.value}}"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Value", name: "value", widget: "number" }

      - label: "rating"
        name: "rating"
        widget: "object"
        summary: "{{fields.key}}: {{fields.value}}"
        fields:
          - { label: "Result", name: "key", widget: "string" }
          - { label: "Note", name: "value", widget: "number" }
      - label: "guarantee"
        name: "guarantee"
        widget: "object"
        summary: "{{fields.key}}: {{fields.value}}"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Value", name: "value", widget: "number" }
          - { label: "baseUnit", name: "baseUnit", widget: "string" }
      - label: "subsidies"
        name: "subsidies"
        widget: "object"
        summary: "{{fields.key}}: {{fields.value}}"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Value", name: "value", widget: "number" }
          - { label: "baseUnit", name: "baseUnit", widget: "string" }
      - label: "battery-guarantee"
        name: "batteryGuarantee"
        widget: "object"
        summary: "{{fields.key}}: {{fields.value}}"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Value", name: "value", widget: "number" }
          - { label: "Weeks", name: "baseUnit", widget: "string" }
      - label: "Car-Sizes"
        name: "carSizes"
        widget: "object"
        summary: "{{fields.height}}: {{fields.width}}: {{fields.length}}"
        fields:
          - { label: "Key", name: "Key", widget: "string" }
          - { label: "height", name: "height", widget: "string" }
          - { label: "height-Value", name: "valueheight", widget: "number" }

          - { label: "width", name: "width", widget: "string" }
          - { label: "width-Value", name: "valuewidth", widget: "number" }

          - { label: "length", name: "length", widget: "string" }
          - { label: "length-Value", name: "valuelength", widget: "number" }
          - { label: "baseUnit", name: "baseUnit", widget: "string" }
      - label: "loadingVolume"
        name: "loadingVolume"
        widget: "object"
        summary: "{{fields.height}}: {{fields.width}}: {{fields.length}}"
        fields:
          - { label: "Key", name: "Key", widget: "string" }
          - { label: "height", name: "height", widget: "string" }
          - { label: "height-Value", name: "valueheight", widget: "number" }

          - { label: "width", name: "width", widget: "string" }
          - { label: "width-Value", name: "valuewidth", widget: "number" }

          - { label: "length", name: "length", widget: "string" }
          - { label: "length-Value", name: "valuelength", widget: "number" }
          - { label: "baseUnit", name: "baseUnit", widget: "string" }
      
