backend:
  name: github
  repo: ari-motors-team/elektrotransporter-vergleich
  branch: dev
  base_url: https://preview-elektrotransporter-vergleich.vercel.app
  # auth_endpoint: api/auth
  # auth_type: pkce
  # app_id: aac348df96d3bb0a9253a7124cbe6af595c462fcfcdc36a09b0d0616c81eebe0

media_folder: public/images
public_folder: /images
local_backend: true

i18n:
  structure: multiple_folders
  locales: [en, de]
  default_locale: en

collections:
  - label: "Pages"
    name: "pages"
    identifier_field: path
    folder: "content/pages"
    create: true
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Path", name: "path", widget: "string", i18n: duplicate }
      - label: "Description"
        name: "description"
        widget: "text"
        i18n: true
      - {
          label: Image,
          name: src,
          widget: image,
          i18n: duplicate,
          choose_url: true,
        }
      - label: "Content"
        name: "content"
        widget: "list"
        summary: "{{fields.name}}"
        i18n: true
        required: false
        fields:
          - { label: "Name", name: "name", widget: "string", i18n: true }
          - { label: "Markdown", name: "markdown", widget: "markdown" }

  - label: "Blog"
    name: "blog"
    folder: "content/posts"
    create: true
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Slug", name: "slug", widget: "string", i18n: duplicate }
      - label: "Published at"
        name: "publishedAt"
        widget: "date"
        default: ""
        format: "MM/DD/YYYY"
        i18n: true
      - label: "Description"
        name: "description"
        widget: "text"
        i18n: true
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        choose_url: true
        media_library:
          config:
            multiple: true
      - { label: "Preview", name: "preview", widget: "text", i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }

  - label: "Add Vehicles"
    name: "vehicles"
    folder: "content/vehicles"
    create: true
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }

      - { label: "Price", name: "price", widget: "number", i18n: duplicate }
      # - label: "Published at"
      #   name: "publishedAt"
      #   widget: "date"
      #   default: ""
      #   format: "MM/DD/YYYY"
      #   i18n: true
      - label: "Description"
        name: "description"
        widget: "markdown"
        i18n: true
      - { label: Image, name: src, widget: image, i18n: duplicate }
      - { label: "Preview", name: "preview", widget: "text", i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
      - label: "Category"
        name: "category"
        widget: "select"
        multiple: false
        i18n: duplicate
        options: ["Pritsche", "Kipper", "Kasten", "Koffer"]
      - label: "Type-Class"
        name: "typeClass"
        widget: "select"
        multiple: false
        i18n: duplicate
        options: ["L7E", "L6E", "N1", "N1N2", "N2"]
        # default: ["Design"]
      - label: "Loadingweight"
        name: "loadingWeight"
        widget: "object"
        summary: "{{fields.key}}: {{fields.value}}"
        i18n: true
        fields:
          - { label: "Key", name: "key", widget: "string", i18n: true }
          - { label: "Value", name: "value", widget: "number", i18n: duplicate }
          - {
              label: "baseUnit",
              name: "baseUnit",
              widget: "string",
              i18n: duplicate,
            }
      - label: "Curb Weight"
        name: "curbweight"
        widget: "object"
        summary: "{{fields.key}}: {{fields.value}}"
        i18n: true
        fields:
          - { label: "key", name: "key", widget: "string", i18n: true }
          - { label: "Value", name: "value", widget: "number", i18n: duplicate }
          - {
              label: "baseUnit",
              name: "baseUnit",
              widget: "string",
              i18n: duplicate,
            }
      - label: "maxSpeed"
        name: "maxSpeed"
        widget: "object"
        summary: "{{fields.key}}: {{fields.value}}"
        i18n: true
        fields:
          - { label: "Key", name: "key", widget: "string", i18n: true }
          - { label: "Value", name: "value", widget: "number", i18n: duplicate }
          - {
              label: "baseUnit",
              name: "baseUnit",
              widget: "string",
              i18n: duplicate,
            }
      - label: "Range-230V"
        name: "range230V"
        widget: "object"
        summary: "{{fields.key}}: {{fields.value}}"
        i18n: true
        fields:
          - { label: "Key", name: "key", widget: "string", i18n: true }
          - { label: "Value", name: "value", widget: "number", i18n: duplicate }
          - {
              label: "baseUnit",
              name: "baseUnit",
              widget: "string",
              i18n: duplicate,
            }
      - label: "Range-Lithium"
        name: "rangeLithium"
        widget: "object"
        summary: "{{fields.key}}: {{fields.value}}"
        i18n: true
        fields:
          - { label: "Key", name: "key", widget: "string", i18n: true }
          - { label: "Value", name: "value", widget: "number", i18n: duplicate }
          - {
              label: "baseUnit",
              name: "baseUnit",
              widget: "string",
              i18n: duplicate,
            }
      - label: "chargingTime-230V"
        name: "chargingTime230V"
        widget: "object"
        summary: "{{fields.key}}: {{fields.value}}"
        i18n: true
        fields:
          - { label: "Key", name: "key", widget: "string", i18n: true }
          - { label: "Value", name: "value", widget: "number", i18n: duplicate }
          - {
              label: "baseUnit",
              name: "baseUnit",
              widget: "string",
              i18n: duplicate,
            }
      - label: "chargingTime-Lithium"
        name: "chargingTimeLithium"
        widget: "object"
        summary: "{{fields.key}}: {{fields.value}}"
        i18n: true
        fields:
          - { label: "Key", name: "key", widget: "string", i18n: true }
          - { label: "Value", name: "value", widget: "number", i18n: duplicate }
          - {
              label: "baseUnit",
              name: "baseUnit",
              widget: "string",
              i18n: duplicate,
            }
      - label: "chargingTime-Fast"
        name: "chargingTimeFast"
        widget: "object"
        summary: "{{fields.key}}: {{fields.value}}"
        i18n: true
        fields:
          - { label: "Key", name: "key", widget: "string", i18n: true }
          - { label: "Value", name: "value", widget: "number", i18n: duplicate }
          - {
              label: "baseUnit",
              name: "baseUnit",
              widget: "string",
              i18n: duplicate,
            }
      - label: "battery-Capacity"
        name: "batteryCapacity"
        widget: "object"
        summary: "{{fields.key}}: {{fields.value}}"
        i18n: true
        fields:
          - { label: "Key", name: "key", widget: "string", i18n: true }
          - { label: "Value", name: "value", widget: "number", i18n: duplicate }
          - {
              label: "baseUnit",
              name: "baseUnit",
              widget: "string",
              i18n: duplicate,
            }
      - label: "Seats"
        name: "seats"
        widget: "object"
        summary: "{{fields.key}}: {{fields.value}}"
        i18n: true
        fields:
          - { label: "Key", name: "key", widget: "string", i18n: true }
          - { label: "Value", name: "value", widget: "number", i18n: duplicate }

      - label: "rating"
        name: "rating"
        widget: "object"
        summary: "{{fields.key}}: {{fields.value}}"
        i18n: true
        fields:
          - { label: "Result", name: "key", widget: "string", i18n: true }
          - { label: "Note", name: "value", widget: "number", i18n: duplicate }
      - label: "guarantee"
        name: "guarantee"
        widget: "object"
        summary: "{{fields.key}}: {{fields.value}}"
        i18n: true
        fields:
          - { label: "Key", name: "key", widget: "string", i18n: true }
          - { label: "Value", name: "value", widget: "number", i18n: duplicate }
          - {
              label: "baseUnit",
              name: "baseUnit",
              widget: "string",
              i18n: duplicate,
            }
      - label: "availability"
        name: "availability"
        widget: "object"
        summary: "{{fields.key}}: {{fields.value}}"
        i18n: true
        fields:
          - { label: "Key", name: "key", widget: "string", i18n: true }
          - {
              label: "From-When",
              name: "value",
              widget: "string",
              i18n: duplicate,
            }

      - label: "subsidies"
        name: "subsidies"
        widget: "object"
        summary: "{{fields.key}}: {{fields.value}}"
        i18n: true
        fields:
          - { label: "Key", name: "key", widget: "string", i18n: true }
          - { label: "Value", name: "value", widget: "number", i18n: true }
          - {
              label: "baseUnit",
              name: "baseUnit",
              widget: "string",
              i18n: duplicate,
            }
      - label: "battery-guarantee"
        name: "batteryGuarantee"
        widget: "object"
        summary: "{{fields.key}}: {{fields.value}}"
        i18n: true
        fields:
          - { label: "Key", name: "key", widget: "string", i18n: true }
          - { label: "Value", name: "value", widget: "number", i18n: duplicate }
          - {
              label: "Weeks",
              name: "baseUnit",
              widget: "string",
              i18n: duplicate,
            }
      - label: "Car-Sizes"
        name: "carSizes"
        widget: "object"
        summary: "{{fields.height}}: {{fields.width}}: {{fields.length}}"
        i18n: true
        fields:
          - { label: "Key", name: "key", widget: "string", i18n: true }
          - { label: "height", name: "height", widget: "string", i18n: true }
          - {
              label: "height-Value",
              name: "valueheight",
              widget: "number",
              i18n: duplicate,
            }

          - { label: "width", name: "width", widget: "string", i18n: true }
          - {
              label: "width-Value",
              name: "valuewidth",
              widget: "number",
              i18n: duplicate,
            }

          - { label: "length", name: "length", widget: "string", i18n: true }
          - {
              label: "length-Value",
              name: "valuelength",
              widget: "number",
              i18n: duplicate,
            }
          - {
              label: "wheelbase",
              name: "wheelbase",
              widget: "string",
              i18n: true,
            }
          - {
              label: "wheelbase-Value",
              name: "valuewheelbase",
              widget: "number",
              i18n: duplicate,
            }
          - {
              label: "baseUnit",
              name: "baseUnit",
              widget: "string",
              i18n: duplicate,
            }
      - label: "loadingVolume"
        name: "loadingVolume"
        widget: "object"
        summary: "{{fields.height}}: {{fields.width}}: {{fields.length}}"
        i18n: true
        fields:
          - { label: "Key", name: "key", widget: "string", i18n: true }
          - { label: "height", name: "height", widget: "string", i18n: true }
          - {
              label: "height-Value",
              name: "valueheight",
              widget: "number",
              i18n: duplicate,
            }

          - { label: "width", name: "width", widget: "string", i18n: true }
          - {
              label: "width-Value",
              name: "valuewidth",
              widget: "number",
              i18n: duplicate,
            }

          - { label: "length", name: "length", widget: "string", i18n: true }
          - {
              label: "length-Value",
              name: "valuelength",
              widget: "number",
              i18n: duplicate,
            }
          - {
              label: "baseUnit",
              name: "baseUnit",
              widget: "string",
              i18n: duplicate,
            }
