import Head from "next/head";
import getContent from "/utils/getContent";
import { MDXRemote } from "next-mdx-remote";

const components = {
  img: (image) => <Image src={image.src} alt={image.alt} objectFit="contain" />,
  a: (link) => (
    <Link href={link.href}>
      <a>{link.children}</a>
    </Link>
  ),
  h2: (heading) => <h2 className="mb-8 font-black">{heading.children}</h2>,
};

export default function Home(props) {
  return (
    <>
      <Head>
        <title>{props.page.title}</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="manifest" href="./manifest.json" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="font-black max-w-xl lg:mr-16 ">
        <MDXRemote {...props.page.sources.main} components={components} />
      </div>
    </>
  );
}

export async function getStaticProps(context) {
  const pages = await getContent("pages", context.locale);
  const posts = await getContent("posts", context.locale);
  const page = pages.find((page) => page.path === "/");

  if (!page) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      page,
      posts,
    },
  };
}
